### ISSUE TITLE
Doesn't seem to install and run on trusty.

### ISSUE THREAD

**Issue by kitsunde** [softasap/sa-vpn-openvpn#1]
The service `openvpn@server` doesn't exist. If I try to start the service `openvpn` it just fails.

```bash
ubuntu@ip-10-0-0-105:~$ service openvpn status
 * VPN 'server' is not running
ubuntu@ip-10-0-0-105:~$ service openvpn start
 * Starting virtual private network daemon(s)...                                                                                                                                                                                                                                 *   Autostarting VPN 'server'
```

My playbook is just:

```
---
- name: VPN
  hosts: all
  become: yes
  remote_user: ubuntu
  vars:
    openvpn_vpn_users:
      - name: "mediapop"
        password: "sdfsdfdf"
  roles:
    - "openvpn"
```
